# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://marcossantanaioc.github.io/qsar_ad/"

git_url = "https://github.com/marcossantanaioc/qsar_ad/tree/master/"

def custom_doc_links(name): return None
